name: Crypto Altcoin Hunter Daily

on:
  schedule:
  # Agendado para as 10:00 UTC e 15:00 UTC diariamente, o que corresponde a 07:00 AM e 12:00 PM no horário de Brasília, respectivamente.
    # 10:00 UTC = 07:00 AM Brasília
    # 15:00 UTC = 12:00 PM Brasília
    - cron: '0 10,15 * * *'
  workflow_dispatch: # Permite que você rode o bot manualmente pelo botão "Run workflow" no GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pandas-ta

      - name: Rodar Altcoin Bot
        env:
          # Conecta os Secrets que você cadastrou no GitHub ao código
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python altcoin_bot.py